[[redirects]]
  from = "/api/*"
  to = "https://imhele.com/bjtu-papms/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
